site_name: Read📖Guides
site_url: https://www.redguides.com/docs
repo_url: https://github.com/RedGuides/readguides
theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunset-down
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: light blue
      accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: light blue
      accent: red
  logo: img/logomaterial.svg
  favicon: img/favicon.ico
  icon:
    admonition:
      abstract: material/torch

extra_css:
  - stylesheets/extra.css

hooks:
  - hooks/mkdocs_hooks.py
  - hooks/optional_hooks.py

plugins:
  - search
  - awesome-nav
  - glightbox
  - include-markdown
  - macros
  - meta
  - privacy
  - tags

validation:
  unrecognized_links: ignore

markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets:
    check_paths: true
    url_download: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde

extra_javascript:
    - js/random-image.js

exclude_docs: |
  /projects/macroquest/README.md
  /projects/macroquest/plugins/community-plugins/
  /projects/macroquest/vendor/
  /projects/macroquest/plugins/discontinued/
  /projects/macroquest/macros/gallery/
  /projects/macroquest/reference/commands/eq/
  /projects/macroquest/main/**
  !/projects/macroquest/main/macroquest.ini.md
  !/projects/macroquest/main/macroquest-launcher.md
  !/projects/macroquest/main/hacker-stuff.md
  !/projects/macroquest/main/history-of-macroquest.md
  !/projects/macroquest/main/other-applications/text-editors/vscode-syntax-file.md
  !/projects/macroquest/main/building.md
  !/projects/macroquest/main/plugin-quick-list.md
  !/projects/macroquest/main/features/**
  !/projects/macroquest/main/developing/**
  /projects/aqo/README.md
  /projects/aqo/main/
  /projects/aqo/misc/
  /projects/aqo/aqobot/
  /projects/aqo/debugger/
  /projects/aqo/luabard/
  /projects/aqo/luanecro/
  /projects/aqo/abilitypicker/
  /projects/aqo/taskwindow/
  /projects/aqo/arkanoid/
  /projects/aqo/wordquest/