nav:
  - Main Page: index.md

  - MacroQuest:
    - MacroQuest Commands:
      - Slash Commands:
        - glob: "projects/macroquest/reference/commands/*.md"
          ignore: README.md
          sort:
            by: filename
            direction: asc
      - Macro Commands:
        - /break: projects/macroquest/reference/commands/break.md
        - /deletevar: projects/macroquest/reference/commands/deletevar.md
        - /delay: projects/macroquest/reference/commands/delay.md
        - /declare: projects/macroquest/reference/commands/declare.md
        - /call: projects/macroquest/reference/commands/call.md
        - /clearerrors: projects/macroquest/reference/commands/clearerrors.md
        - /continue: projects/macroquest/reference/commands/continue.md
        - /doevents: projects/macroquest/reference/commands/doevents.md
        - /endmacro: projects/macroquest/reference/commands/endmacro.md
        - /for: projects/macroquest/reference/commands/for.md
        - /goto: projects/macroquest/reference/commands/goto.md
        - /if: projects/macroquest/reference/commands/if.md
        - /invoke: projects/macroquest/reference/commands/invoke.md
        - /listmacros: projects/macroquest/reference/commands/listmacros.md
        - /macro: projects/macroquest/reference/commands/macro.md
        - /mqpause: projects/macroquest/reference/commands/mqpause.md
        - /next: projects/macroquest/reference/commands/next.md
        - /return: projects/macroquest/reference/commands/return.md
        - /seterror: projects/macroquest/reference/commands/seterror.md
        - /varcalc: projects/macroquest/reference/commands/varcalc.md
        - /vardata: projects/macroquest/reference/commands/vardata.md
        - /varset: projects/macroquest/reference/commands/varset.md
        - /while: projects/macroquest/reference/commands/while.md
    - MacroQuest TLOs: projects/macroquest/reference/top-level-objects
    - MacroQuest DataTypes: projects/macroquest/reference/data-types
    - Core Plugins: http://127.0.0.1:8000/projects/macroquest/plugins/core-plugins/
  - Plugins:
    - Core Plugins: projects/macroquest/plugins/core-plugins
    - glob: "projects/mq*"
      preserve_directory_names: true
      sort:
        by: filename
        direction: asc
  - Scripts:
    - projects/kissassist
    - projects/aqo/*
  - /commands: commands/index.md
  - TLOs: tlos/index.md
